### ISSUE TITLE
Banco de dados único

### ISSUE THREAD

**Issue by fulvionedel** [rfsaldanha/brpop#1]
Olá Raphael

Obrigado por mais esse trabalho, grande iniciativa. Teus pacotes nos facilitam muito a vida :)
Acho que seria bom também incluir um banco único com todas as informações por município, porque muitas vezes o manejo e análise dos dados exigem a organização das informações nessa forma. Criei esse script pra isso, vê o que achas. A propósito, trabalhando em bancos com informação detalhada da idade (AIH, DO, ...), considera minha função `csapAIH::fxetar_quinq()` pra classificação de faixas etárias quinquenais com diferentes limites de idade.

Obrigado novamente, já dá pra citar?

PS: não entendo direito o GitHub, espero que este "issue/pull request" funcione!

**Comment by rfsaldanha** [comment]
Olá Fulvio! Obrigado pela contribuição. Creio que com as novas funções que adicionei, consegui atender essa demanda.
