### ISSUE TITLE
`mun_pop_totals` retornando valores duplicados

### ISSUE THREAD

**Issue by filipemsc** [rfsaldanha/brpop#5]
Rodei o comando `mun_pop_totals` e recebi uma tabela com valores duplicados, vide exemplo:

![image](https://user-images.githubusercontent.com/11773789/199969161-7d0ebb16-ad1c-4bcb-99ff-685adb71c5c1.png)

Note que cada município aparece 2x por ano, às vezes com valores diferentes.

**Comment by filipemsc** [comment]
Pelo que eu entendi, o problema está no fato de que a função deveria estar somando o total de homens e mulheres:

https://github.com/rfsaldanha/brpop/blob/main/R/mun_pop_totals.R

**Comment by rfsaldanha** [comment]
Obrigado pelo pull request Filipe!
