### ISSUE TITLE
Import availableCores() from parallelly instead of future

### ISSUE THREAD

**Issue by HenrikBengtsson** [rfsaldanha/brpop#9]
It looks like you depend on the **future** package, because `future::availableCores()`.  Please note that that function has moved to **parallelly**.    The one in **future** is simply a direct re-export of the one in **parallelly**.

If you update your code to use `parallelly::availableCores()` instead, you're package will have fewer indirect dependencies (that otherwise come with the **future** package).

**Comment by rfsaldanha** [comment]
Thanks for the update! The next release will no longer depend on parallel computation.
